# .sops.yaml is generated: every enrolled host key (see host-keys.nix) can
# decrypt secrets/shared.yaml, and each host its own secrets/hosts/<name>.yaml.
# `just secrets-rekey` writes it and re-encrypts.
{ config, lib, ... }:
let
  # The admin key's public half; its private half is the 1Password
  # document sops-admin.
  admin = "age1uer6slgawhqvrymlsw8q57jrqa23xy2vh9zhfmx2dvmk6s7x8qgqrgznpc";
  names = lib.attrNames config.hostKeys;
in
{
  perSystem =
    { pkgs, ... }:
    {
      packages.sops-config = pkgs.runCommand "sops.yaml" { nativeBuildInputs = [ pkgs.ssh-to-age ]; } ''
        {
          echo "# Generated by \`just secrets-rekey\` from modules/hosts/_host-keys.json; don't edit."
          echo "keys:"
          echo "  - &admin ${admin}"
          ${lib.concatMapStrings (n: ''
            echo "  - &${n} $(echo ${lib.escapeShellArg config.hostKeys.${n}} | ssh-to-age)"
          '') names}
          echo "creation_rules:"
          echo "  - path_regex: ^secrets/shared\\.yaml$"
          echo "    age: [${lib.concatMapStringsSep ", " (n: "*${n}") ([ "admin" ] ++ names)}]"
          ${lib.concatMapStrings (n: ''
            echo "  - path_regex: ^secrets/hosts/${n}\\.yaml$"
            echo "    age: [*admin, *${n}]"
          '') names}
        } > $out
      '';
    };
}
