# .sops.yaml is generated: every enrolled host key (see host-keys.nix) can
# decrypt secrets/shared.yaml, and each host its own secrets/hosts/<name>.yaml.
# `just secrets-rekey` writes it and re-encrypts; a check keeps the committed
# copy in sync.
{ config, lib, ... }:
let
  # The recovery key's public half; its private half is the 1Password
  # document sops-recovery.
  recovery = "age1uer6slgawhqvrymlsw8q57jrqa23xy2vh9zhfmx2dvmk6s7x8qgqrgznpc";
  names = lib.attrNames config.hostKeys;
in
{
  perSystem =
    { pkgs, ... }:
    let
      sopsConfig = pkgs.runCommand "sops.yaml" { nativeBuildInputs = [ pkgs.ssh-to-age ]; } ''
        {
          echo "# Generated by \`just secrets-rekey\` from modules/hosts/_host-keys.json; don't edit."
          echo "keys:"
          echo "  - &recovery ${recovery}"
          ${lib.concatMapStrings (n: ''
            echo "  - &${n} $(echo ${lib.escapeShellArg config.hostKeys.${n}} | ssh-to-age)"
          '') names}
          echo "creation_rules:"
          echo "  - path_regex: ^secrets/shared\\.yaml$"
          echo "    age: [${lib.concatMapStringsSep ", " (n: "*${n}") ([ "recovery" ] ++ names)}]"
          ${lib.concatMapStrings (n: ''
            echo "  - path_regex: ^secrets/hosts/${n}\\.yaml$"
            echo "    age: [*recovery, *${n}]"
          '') names}
        } > $out
      '';
    in
    {
      packages.sops-config = sopsConfig;
      checks.sops-config = pkgs.runCommand "sops-config-in-sync" { } ''
        if ! diff -u ${../../.sops.yaml} ${sopsConfig}; then
          echo ".sops.yaml is out of date with modules/hosts/_host-keys.json; run: just secrets-rekey" >&2
          exit 1
        fi
        touch $out
      '';
    };
}
