model = "gpt-5-codex"
model_reasoning_effort = "high"

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp"]
command = "npx"

[mcp_servers.convex]
args = ["npx", "-y", "convex@latest", "mcp", "start"]
command = "npx"
